apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: flux-system
resources:
  - receiver.yaml
  - github-repo.yaml
  - group-core.yaml
  #- group-infra.yaml
  #- group-apps.yaml
