apiVersion: v1
kind: Service
metadata:
  name: versitygw
  labels:
    app.kubernetes.io/name: versitygw
    app.kubernetes.io/instance: test
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: versitygw
    app.kubernetes.io/instance: test
