---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ghost
  labels:
    app.kubernetes.io/name: ghost
    app.kubernetes.io/version: 3.32.2
    app.kubernetes.io/component: server
    app.kubernetes.io/managed-by: argocd
  namespace: blog
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: ghost
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app.kubernetes.io/name: ghost
        app.kubernetes.io/version: 3.32.2
        app.kubernetes.io/component: server
        app.kubernetes.io/managed-by: argocd
    spec:
      containers:
      - name: ghost
        image: ghost:3.32.2
        ports:
          - name: http
            containerPort: 2368
        env:
          - name: url
            value: https://alchemyof.it
        livenessProbe:
          tcpSocket:
            port: 2368
          initialDelaySeconds: 30
          periodSeconds: 60
          timeoutSeconds: 5
        volumeMounts:
          - mountPath: /var/lib/ghost/content
            name: content
        resources:
          requests:
            memory: 120M
        securityContext:
          readOnlyRootFilesystem: true
          runAsNonRoot: true
      volumes:
        - name: content
          persistentVolumeClaim:
            claimName: ghost
