apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: slack-url
  namespace: flux-system
spec:
  encryptedData:
    address: AgB3z3Wy9Qq/g4AWs0XSinYAaTnqr0uIODOZWna9yDmqda+MD8dkxmrtCpE/NIFnYBxhQuh9m181zDSUntXtUZ10eR9QmTyFwQgk7GZ9g+xbK1kd/gPOg+omymgfXkKxp1HWNPbBGDLPU0BYHMPtzfLoG+Vy+tDHacd2xS36YLEhFsn89LjzwdMqBFdnTMi5qe45hmu2+CtzhKeIUX8jtQz89HN8gCTpTj8DqkcyvS9iGPN5yEGlesOqMEwDXILKUAhy9rE7Htr9RVSXnLzl2bpJwSkgoC3iG9pbm+zaHkXffk+OxLzRJTqKgQqJ7gMOzyb8HIFzM/djTYV2dJTaQDzyceNYHrW0kmMbFjqTdrT922ess2k/nUFfNO7rLwtJ4ONxu8z3XWfMZCTGzWospc3XDGVoIrLOwOnNifvkz49OJrAJPtj0HQQ0t5eVXaw5sF2HhUoA0ENlYiEU124syFHCmCDA8uqoedspswX8appm9zkYkxKshlZ90Rfawj7AJfuJxUkKUF7lGY/zfLyEruScayucPQ8yTw+JUj192Gal4t5oErrdoG9PL2THLhHaKl1Gdyo643S9DaLYMfLomNe/68nA5kFy9CScL3vHlHrVT921CGxrECkHYOJg8h0g8YrLzAuhV1cTHfG8TBV4FNkkxhQrvKg33CmE9bAJrdLs0S7TS5ko31T0rnBe2cDyMX5BnRuBCHih08KApaI2CcnzsEH9GEb0fRszVZgaGlP2Q69+LNxoYVuZofdmAnfJfK/7HPg+FlLGSciV1MtON/mipWzKITvfgTLgtKrk+EFG 
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: slack-url
      namespace: flux-system
