apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: topolvm-system
resources:
  - repository.yaml
  - release.yaml
  - prometheusrules.yaml
configMapGenerator:
  - name: values
    files:
      - values.yaml=values.yaml
configurations:
  - kustomizeconfig.yaml
