apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/component: server
    app.kubernetes.io/name: jackett
    app.kubernetes.io/part-of: jackett
    app.kubernetes.io/version: 0.20.236
  name: jackett
  namespace: multimedia
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/component: server
      app.kubernetes.io/name: jackett
      app.kubernetes.io/part-of: jackett
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app.kubernetes.io/component: server
        app.kubernetes.io/name: jackett
        app.kubernetes.io/part-of: jackett
        app.kubernetes.io/version: 0.20.236
    spec:
      containers:
      - image: linuxserver/jackett:0.20.236
        imagePullPolicy: IfNotPresent
        livenessProbe:
          initialDelaySeconds: 30
          periodSeconds: 60
          tcpSocket:
            port: 9117
          timeoutSeconds: 5
        name: jackett
        ports:
        - containerPort: 9117
          name: http
        resources:
          limits:
            cpu: 3000m
            memory: 350Mi
          requests:
            cpu: 2400m
            memory: 200Mi
        volumeMounts:
        - mountPath: /config
          name: config
      restartPolicy: Always
      securityContext:
        fsGroup: 1000
      serviceAccountName: jackett
      volumes:
      - name: config
        persistentVolumeClaim:
          claimName: jackett
