apiVersion: v1
automountServiceAccountToken: false
kind: ServiceAccount
metadata:
  labels:
    app.kubernetes.io/component: server
    app.kubernetes.io/name: jackett
    app.kubernetes.io/part-of: jackett
    app.kubernetes.io/version: 0.20.238
  name: jackett
  namespace: multimedia
