apiVersion: v1
kind: Service
metadata:
  annotations:
    metallb.universe.tf/address-pool: default
    metallb.universe.tf/allow-shared-ip: multimedia-svc
  labels:
    app.kubernetes.io/component: server
    app.kubernetes.io/name: jackett
    app.kubernetes.io/part-of: jackett
    app.kubernetes.io/version: 0.18.547
  name: jackett
  namespace: multimedia
spec:
  externalTrafficPolicy: Cluster
  loadBalancerIP: 192.168.2.95
  ports:
  - name: http
    port: 9117
    targetPort: http
  selector:
    app.kubernetes.io/component: server
    app.kubernetes.io/name: jackett
    app.kubernetes.io/part-of: jackett
  sessionAffinity: None
  type: LoadBalancer
