apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/proxy-body-size: 600K
  labels:
    app.kubernetes.io/component: server
    app.kubernetes.io/name: ghost
    app.kubernetes.io/part-of: ghost
    app.kubernetes.io/version: 4.7.0
    probe: enabled
  name: ghost
  namespace: blog
spec:
  rules:
  - host: pawel.krupa.net.pl
    http:
      paths:
      - backend:
          service:
            name: ghost
            port:
              name: http
        path: /
        pathType: Prefix
  tls:
  - hosts:
    - pawel.krupa.net.pl
    secretName: ghost-tls
