apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/component: server
    app.kubernetes.io/name: ghost
    app.kubernetes.io/part-of: ghost
    app.kubernetes.io/version: 4.8.4
  name: ghost
  namespace: blog
spec:
  clusterIP: None
  ports:
  - name: http
    port: 2368
    targetPort: http
  selector:
    app.kubernetes.io/component: server
    app.kubernetes.io/name: ghost
    app.kubernetes.io/part-of: ghost
