apiVersion: v1
automountServiceAccountToken: false
kind: ServiceAccount
metadata:
  labels:
    app.kubernetes.io/component: server
    app.kubernetes.io/name: ghost
    app.kubernetes.io/part-of: ghost
    app.kubernetes.io/version: 4.22.4
  name: ghost
  namespace: blog
