apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: grafana-admin-creds
spec:
  data:
  - remoteRef:
      key: GRAFANA_ADMIN_USER
    secretKey: admin-user
  - remoteRef:
      key: GRAFANA_ADMIN_PASSWORD
    secretKey: admin-password
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: doppler-auth-api
