apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: grafana-oidc
spec:
  data:
    - remoteRef:
        key: GRAFANA_OIDC_CLIENT_SECRET
      secretKey: clientSecret
    - remoteRef:
        key: GRAFANA_OIDC_CLIENT_ID
      secretKey: clientID
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: doppler-auth-api
