apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: movies
  namespace: multimedia
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 4000Gi
  storageClassName: manual
  volumeName: movies
