apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/component: server
    app.kubernetes.io/name: mealie
    app.kubernetes.io/part-of: mealie
    app.kubernetes.io/version: 0.5.3
  name: mealie
  namespace: recipe
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/component: server
      app.kubernetes.io/name: mealie
      app.kubernetes.io/part-of: mealie
  template:
    metadata:
      labels:
        app.kubernetes.io/component: server
        app.kubernetes.io/name: mealie
        app.kubernetes.io/part-of: mealie
        app.kubernetes.io/version: 0.5.3
    spec:
      containers:
      - env:
        - name: DB_TYPE
          value: sqlite
        envFrom:
        - secretRef:
            name: envs
        image: hkotel/mealie:v0.5.3
        imagePullPolicy: IfNotPresent
        name: mealie
        ports:
        - containerPort: 80
          name: http
        resources:
          limits:
            cpu: 200m
            memory: 300Mi
          requests:
            cpu: 54m
            memory: 150Mi
        volumeMounts:
        - mountPath: /app/data
          name: appdata
      restartPolicy: Always
      serviceAccountName: mealie
      volumes:
      - name: appdata
        persistentVolumeClaim:
          claimName: mealie
