apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/proxy-body-size: 2M
  labels:
    app.kubernetes.io/component: server
    app.kubernetes.io/name: mealie
    app.kubernetes.io/part-of: mealie
    app.kubernetes.io/version: 0.5.3
    probe: enabled
  name: mealie
  namespace: recipe
spec:
  rules:
  - host: recipe.krupa.net.pl
    http:
      paths:
      - backend:
          service:
            name: mealie
            port:
              name: http
        path: /
        pathType: Prefix
  tls:
  - hosts:
    - recipe.krupa.net.pl
    secretName: mealie-tls
