apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/component: server
    app.kubernetes.io/name: mealie
    app.kubernetes.io/part-of: mealie
    app.kubernetes.io/version: 0.5.3
  name: envs
  namespace: recipe
spec:
  encryptedData:
    DEFAULT_EMAIL: AgACkYL+SnF85iVggdGLS5Sf7ULraJCi13w37EIlZttHwkol69xg7evjs47HGju+YViUGF5BNHpr/VD/uhrX+A0Ix+FIUfbVFiJcXaIBbEKlu9rNw38vAwFYFTiW/0DDybfV5epVTfBFYqRJvNGEbGPukbAwuFq4cfjul2M8NRwXVLzoKDbpsT5rkOCF+TvjO+Vp5tPgzMRX4SIDDdbnlhQqYdS0rmKzLbn+28arV8zSxrnO2LxaP6bPPS6CvDow7o9FRbw5GyD4yiDTCo4s6Lv7bG1bkPgTJdBFlApQFBW4Tt3CUNgFuFPcMeNulQJwjW6H50J683CvKJ4AO7YPlRtonaHZweIhK0JSDg7LSdXysBqYogdqjMH6K/B21Y5a9mex4+1rM1kRj8vsCOWx4T3+b7MAQYdyA4HwlFXJUDzi/mvwLPY7tclUc3LMLSd684bniPvd+91/vvbxzRelu47pJDqdeo07FABQCkdEtE8SOtFRNvLJ7UTefKQBhc2fbOkF8oG/vtqzV8DwZq81MNIynWx03Nw+R7mfaIZhtvNcLQS3PghgrUsNawJJMDYm2jqZ1VcYK/V3IxQtModiebeDydoQakzKhjVQI7CT/hPZzCLV3Y7LoaQhZl2zzGHaOXzpsIevzYwt5mHE7rLCSYL5Zn1NmhWVtyKTGa9Vm6sHvG5wGmq1yzEzGdqNEiccoRixBmlgdcpyp+j4Yl1FSrcEyJLpEw==
    DEFAULT_PASSWORD: AgANLJVB3sJjvFNZr1beKm6mU63o0TdMA6jZywKsy5PAkw1ofOoVt8tfkUpq3DMeSZjs9Bi66fhfO74UIaBsAUinQKLDtgiuT2OkT60CbcyQykXV6rV5LYBmwy7z5oTFNlWRbGwQAciHdF992NzbZKTC3S8awmjgH/wWs2hDPXx/GkApOv9UDurPlA+rftMJZ909CIgM1wvhMwjd20firHbJRxp6ICC998juIq+F95yTsGrH2CSOVw6VBxLf3aLE0c2IEJ5Fhwn3Hez8TYFca9mx9hZIbTezKogxAjAb7wf101xlCsZAshp7+mML8Pq7ugwZ9eQTo6byi6p5MQYw/jzz+7jcrkFuySMsnJax/lXffasmaV7zT7R3B7EUstyyJ0tfSJ0YWZS4AStZQlpFVTCcgULZVFt8AL4LO1BO0EVv2NqOLZLd3pmse0BctTNJxgEdl3x3xY6DNEqnJHD0cN5MkmN46a/rg4wx7wEoZTB1/uTQIb+FRYMFYmWLQoNWYkYeTZh8eJB0ACkkYOxdTixsgUpJVn5l3ut5mwnHh79w6RGsUwdau10in46JW0Dz+pwUlYPFK+G0fUwN3Ulzfa7bmR+Z2Xj323jVPmTs0NPXU2MvkrBOHDNCH3mU8YURb5guCIMMpro20b4c43tGBddPOJADRf7Oqy2gTEun8Hh+cJEKLLVu7582gGueaSeBP5uYHB1Y6XSZOb9hSakOlD9KXiZmtg==
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/managed: "true"
      creationTimestamp: null
      labels:
        app.kubernetes.io/component: server
        app.kubernetes.io/name: mealie
        app.kubernetes.io/part-of: mealie
        app.kubernetes.io/version: 0.5.3
      name: envs
      namespace: recipe
