apiVersion: v1
data:
  config.yml: |
    title: "Ankhmorpork portal"
    subtitle: "thaum"
    logo: "logo.png"
    # icon: "fas fa-skull-crossbones" # Optional icon

    header: true
    footer: false

    # Optional theme customization
    theme: default
    colors:
      light:
        highlight-primary: "#3367d6"
        highlight-secondary: "#4285f4"
        highlight-hover: "#5a95f5"
        background: "#f5f5f5"
        card-background: "#ffffff"
        text: "#363636"
        text-header: "#ffffff"
        text-title: "#303030"
        text-subtitle: "#424242"
        card-shadow: rgba(0, 0, 0, 0.1)
        link-hover: "#363636"
      dark:
        highlight-primary: "#3367d6"
        highlight-secondary: "#4285f4"
        highlight-hover: "#5a95f5"
        background: "#131313"
        card-background: "#2b2b2b"
        text: "#eaeaea"
        text-header: "#ffffff"
        text-title: "#fafafa"
        text-subtitle: "#f5f5f5"
        card-shadow: rgba(0, 0, 0, 0.4)
        link-hover: "#ffdd57"

    # Optional message
    #message:
    #  #url: https://b4bz.io
    #  style: "is-dark" # See https://bulma.io/documentation/components/message/#colors for styling options.
    #  title: "Demo !"
    #  icon: "fa fa-grin"
    #  content: "This is a dummy homepage demo. <br /> Find more information on <a href='https://github.com/bastienwirtz/homer'>github.com/bastienwirtz/homer</a>"

    # Optional navbar
    # links: [] # Allows for navbar (dark mode, layout, and search) without any links
    links:
      - name: Status Page
        icon: "fa fa-question"
        url: "https://thaum.statuspage.io/"
      - name: Passwords
        icon: "fa fa-key"
        url: "https://vault.bitwarden.com/"

    tags:
      Local: &Local
        - tag: local
          tagstyle: "is-success"
      Testing: &Testing
        - tag: testing
          tagstyle: "is-danger"

    # Services
    # First level array represent a group.
    # Leave only a "items" key if not using group (group name, icon & tagstyle are optional, section separation will not be displayed).
    services:
      - name: Ankh Cloud
        icon: "fa fa-cloud"
        items:
          - name: Portal
            subtitle: "Main Portal"
            logo: "https://upload.wikimedia.org/wikipedia/commons/0/08/Internet-icon.svg"
            <<: *Testing
            url: "https://portal.krupa.net.pl"
          - name: Nextcloud
            subtitle: "Everything and more"
            logo: "https://avatars0.githubusercontent.com/u/19211038?s=200&v=4"
            url: "https://cloud.krupa.net.pl"
          - name: Cookbook
            subtitle: "Our recipes"
            logo: "https://github.com/hay-kot/mealie/raw/master/docs/docs/assets/img/favicon.png"
            url: "https://recipe.krupa.net.pl"
          - name: HomeAssistant
            subtitle: "Home automation system"
            logo: "https://upload.wikimedia.org/wikipedia/commons/thumb/6/6e/Home_Assistant_Logo.svg/200px-Home_Assistant_Logo.svg.png"
            url: "https://home.ankhmorpork.thaum.xyz/"
          - name: Image Compressor
            subtitle: "Compress images online"
            logo: "https://i.pinimg.com/originals/03/26/bb/0326bbd35c1a159796da144f6f949aaa.jpg"
            url: "https://compressor.io/"
          - name: Seafile
            subtitle: "Cloud Drive"
            logo: "https://de.seafile.com/wp-content/uploads/2018/09/seafile-300x174.png"
            <<: *Testing
            url: "https://seafile.ankhmorpork.thaum.xyz/"
          - name: Miniflux
            subtitle: "Minimalist RSS feed reader"
            logo: "https://avatars.githubusercontent.com/u/10584991?s=200&v=4"
            <<: *Testing
            url: "https://rss.ankhmorpork.thaum.xyz/"

      - name: Multimedia
        icon: "fa fa-tv"
        items:
          - name: Plex
            subtitle: "Video on demand"
            logo: "https://user-images.githubusercontent.com/58919902/70870444-48efc180-1f48-11ea-9994-dff2df2d9484.png"
            # <<: *Local
            # url: "http://192.168.2.98:32400/web/index.html#"
            url: "https://app.plex.tv/"
          - name: Ombi
            subtitle: "Media requests"
            logo: "http://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/ombi.png"
            url: "https://ombi.ankhmorpork.thaum.xyz/"
          - name: Radarr
            subtitle: "Movie collection manager"
            logo: "https://avatars1.githubusercontent.com/u/25025331?s=200&v=4"
            <<: *Local
            url: "http://192.168.2.95:7878/"
          - name: Sonarr
            subtitle: "TV series collection manager"
            logo: "https://avatars3.githubusercontent.com/u/1082903?s=200&v=4"
            <<: *Local
            url: "http://192.168.2.95:8989/"
          - name: Jackett
            subtitle: "API Support for torrent trackers"
            logo: "https://avatars.githubusercontent.com/u/15383019?s=200&v=4"
            <<: *Local
            url: "http://192.168.2.95:9117/"
          - name: Transmission
            subtitle: "downloader"
            logo: "https://avatars3.githubusercontent.com/u/223312?s=200&v=4"
            <<: *Local
            url: "http://192.168.2.95:9091/transmission/web/"
          - name: Photoprism
            logo: "https://dl.photoprism.org/assets/logo/logo-black-bold.svg"
            <<: *Testing
            subtitle: "Photo management"
            url: "http://192.168.2.96"

      - name: Administration
        icon: "fa fa-user-shield"
        items:
          - name: Grafana
            logo: "https://grafana.com/static/img/logos/grafana_logo_swirl-events.svg"
            url: "https://grafana.ankhmorpork.thaum.xyz/"
          - name: Alertmanager
            logo: "https://upload.wikimedia.org/wikipedia/commons/thumb/3/38/Prometheus_software_logo.svg/200px-Prometheus_software_logo.svg.png"
            url: "https://alertmanager.ankhmorpork.thaum.xyz/"
          - name: Prometheus
            logo: "https://upload.wikimedia.org/wikipedia/commons/thumb/3/38/Prometheus_software_logo.svg/200px-Prometheus_software_logo.svg.png"
            url: "https://prometheus.ankhmorpork.thaum.xyz/"
          - name: Pyrra
            logo: "https://avatars.githubusercontent.com/u/87393422?s=200&v=4"
            url: "https://pyrra.ankhmorpork.thaum.xyz"
          - name: Parca
            logo: "https://avatars.githubusercontent.com/u/86306284?s=200&v=4"
            url: "https://parca.ankhmorpork.thaum.xyz/"
          - name: Freshping
            logo: "https://avatars.slack-edge.com/2018-09-03/427590825217_ae87fee1f01a3539733e_512.png"
            url: "https://paulfantom.freshping.io/dashboard"
          - name: Unifi
            logo: "https://dl.ubnt.com/press/Company_Logos/U_Logo/WEB/U_Logo_RGB.png"
            <<: *Local
            url: "https://192.168.2.7:8443/"
          - name: Qnap
            logo: "https://iconape.com/wp-content/files/pm/364831/svg/364831.svg"
            <<: *Local
            url: "https://192.168.2.29/"
          - name: NextDNS
            logo: "https://appteka.store/api/1/icon/get?hash=AfxOnnAVC55q9P8wC41q8i3I9N%2FfQVVHjM4e2r8kVhJuU5GYQJSe3msYMbOpyZDC"
            url: "https://my.nextdns.io/"
          - name: ESPHome
            logo: "https://esphome.io/_static/favicon-512x512.png"
            <<: *Local
            url: "http://192.168.2.94:6052/"
kind: ConfigMap
metadata:
  labels:
    app.kubernetes.io/component: server
    app.kubernetes.io/name: homer
    app.kubernetes.io/part-of: homer
    app.kubernetes.io/version: 21.09.2
  name: homer-config
  namespace: homer
