apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/component: server
    app.kubernetes.io/name: miniflux
    app.kubernetes.io/part-of: miniflux
    app.kubernetes.io/version: 2.0.33
  name: miniflux
  namespace: news
spec:
  encryptedData:
    ADMIN_PASSWORD: AgBraZxeFnZS9whfA3Wdx95QN6uGOlUeeVecNPFQNq74pF8rEcctZNLA4SyF5jexz+3JvuG38b900h5yMM7xfVOHJEf1PZLvBB6H7RaMJXbFMj8gFW6WVBRUrOh8T6Cm/3+PqNreRUVJChO6Jltc1D/62MBAhlZ9SuMrQOd0GN4sqTNR9bZhNvK1unISmWsl2/jODsKAGNj57oXYpxBS66v0xg5UXhueus50dv0YqKto/rQo+PFBQloPxV1pN199ypgg559VG0+xMK0Q4OJFWQtx3dTHXiAYxZkQHB/MI/Go+8/Zq9cQCvMKxcLqoiWd6R1hWqNvW6c7+m/KG7c0fVnOKL2KwZ61VWTXgh0rfLyKc55/adn9aLUHargrGdWNwvl5fmAm8E4IZXADJisVFnxiXpaeY9tL3nDdeiUgCFcbOfFFzdFnFENppoP7uIdhE63bn2qq50HQh2Zf+6D88ld28LmP/n8SSm6JVZKT8IG55SortkYbwhqUoOJl0guOUSKEldGPwofagtb43FgoURDEpEsBnmWvL3Sr5hHMbzT89UL/ArXwowelFV2cvwOGtMNIklVqR0MU3hXRvxVqf09DHSxQ+Af7Kxdni+t3e9VqHzhDg3dhUkiJa/6MI5vHfAu1npOBMT3b7spMVcYD2fvmAl7rqee6K/i5iguCaXw3iGFNBFbLxb/8RJH4AqBqVmbYZC/quH4vxZsjjyg2r6FYWw0mtHNhGrrZERGdCEnptnuAQigN9xBD
    ADMIN_USERNAME: AgCwdCVdKVM9832LU7H8fzMCzsvn1jLXfiMhcGy7m7QKchCoRIqhUakKcVVvVaWy15fYp3bMhSnh5uR/cmFCkjJ9qI/sSBgKsm7lUf6bDN5oy+vJ2TztjE6PVGvuBIsI/gk9YcCmVh1xMMmY2ZaGsyMvbOLLOudF9xUE0x6XWvg/qqTN/E+IRQLItkSSle1xsCR+C1WtYSFP7PyowdgmUMLdvYkjTU2rEmyCDIyChSrAnIPs0xbyri/b0mHYtdv8RfKUwYEmKggB98ZEMTEpY1RsWkYYnUweT+TpJa9iVd5jzKQQWXNkoyREdfAUEWZUF2tmqSh3Vct8Abc/Cth92RKYC7Q2o5rFfEQ2aLiN45YfxEqJrhy0L+Yso85LCUH246JlEFy7j5JxMMtYQTjkzdO5pQmtJvgHKS/Z8rykBsSyBp4oxBfjx6VWHBXdPbbVBnUGwPOzcJAHncdbTjXH/Kiatvl5084a+Uu8Sguatm096k42v23xyzVOSj90AoHRmU0w+yUEjIK+s7oHHwmiqGsmvAylBGimM0AzY1tScpr5hkS1BaXNGzBU8mChf3WVRCE6uvWr69wxHRyPRs6vDwjoJtBm2RMZbg0OF1x1KdRplE94mKpj4V7kkqRhNDZFyx2MY6sP1DT77nzry7tVNH+YG3Jj+eFNWasORyp8O8/moOO+6XOs64tHesySgkCyhJuNqB0VAQ==
  template:
    data:
      BASE_URL: https://rss.ankhmorpork.thaum.xyz
      CREATE_ADMIN: "1"
      METRICS_ALLOWED_NETWORKS: 10.42.0.1/16
      METRICS_COLLECTOR: "1"
      POSTGRES_SVC: postgres.news.svc
      RUN_MIGRATIONS: "1"
    metadata:
      annotations:
        sealedsecrets.bitnami.com/managed: "true"
      creationTimestamp: null
      labels:
        app.kubernetes.io/component: server
        app.kubernetes.io/name: miniflux
        app.kubernetes.io/part-of: miniflux
        app.kubernetes.io/version: 2.0.33
      name: miniflux
      namespace: news
