---
- name: updating hostname (1/2)
  hostname:
    name: "{{ system_hostname }}"

- name: updating hostname (2/2)
  copy:
    content: "{{ system_hostname }}{{'\n'}}"
    dest: /etc/hostname
    backup: true

- name: update /etc/hosts
  lineinfile:
    dest: /etc/hosts
    regexp: '^127\.0\.0\.1'
    line: "127.0.0.1{{'\t'}}localhost {{ system_hostname }}"
    backup: true
    state: present
