---
apiVersion: "cilium.io/v2alpha1"
kind: CiliumLoadBalancerIPPool
metadata:
  name: bgp-ip-pool
spec:
  blocks:
    - start: "192.168.50.128"
      stop: "192.168.50.254"
  #serviceSelector:
  #  matchLabels:
  #    advertise: bgp
