apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: karakeep-secrets
  namespace: karakeep
spec:
  data:
    - secretKey: NEXTAUTH_SECRET
      remoteRef:
        key: KARAKEEP_NEXTAUTH_SECRET
    - secretKey: NEXT_PUBLIC_SECRET
      remoteRef:
        key: KARAKEEP_NEXT_PUBLIC_SECRET
    - secretKey: MEILI_MASTER_KEY
      remoteRef:
        key: KARAKEEP_MEILI_MASTER_KEY
    - secretKey: OPENAI_API_KEY
      remoteRef:
        key: KARAKEEP_OPENAI_API_KEY
    - secretKey: PROMETHEUS_AUTH_TOKEN
      remoteRef:
        key: KARAKEEP_PROMETHEUS_AUTH_TOKEN
    - secretKey: KARAKEEP_OIDC_CLIENT_ID
      remoteRef:
        key: KARAKEEP_OIDC_CLIENT_ID
    - secretKey: OAUTH_CLIENT_SECRET
      remoteRef:
        key: OAUTH_CLIENT_ID
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: doppler-auth-api
