---
apiVersion: v1
kind: ConfigMap
metadata:
  name: transmission-config
  namespace: multimedia
data:
  LOCAL_NETWORK: 192.168.2.0/24
  TZ: "Europe/Berlin"
  PUID: "1000"
  PGID: "1000"
  OPENVPN_OPTS: "--inactive 3600 --ping 10 --ping-exit 60 --mssfix 1452"
  OPENVPN_PROVIDER: "NORDVPN"
  NORDVPN_COUNTRY: "CH"
  LOG_TO_STDOUT: "true"
  TRANSMISSION_WEB_UI: "combustion"
  TRANSMISSION_RATIO_LIMIT: "0.001"
  # TRANSMISSION_RATIO_LIMIT: "1"
  TRANSMISSION_RATIO_LIMIT_ENABLED: "true"
  TRANSMISSION_RPC_HOST_WHITELIST_ENABLED: "false"
  TRANSMISSION_RPC_WHITELIST_ENABLED: "false"
  TRANSMISSION_DOWNLOAD_QUEUE_SIZE: "2"
  TRANSMISSION_DOWNLOAD_DIR: "/download/completed"
  TRANSMISSION_INCOMPLETE_DIR: "/download/incomplete"
  TRANSMISSION_SPEED_LIMIT_DOWN_ENABLED: "true"
  TRANSMISSION_SPEED_LIMIT_DOWN: "10000"  # kB/s
  TRANSMISSION_ALT_SPEED_DOWN: "5000"  # kB/s
  TRANSMISSION_ALT_SPEED_TIME_ENABLED: "true"
  TRANSMISSION_ALT_SPEED_TIME_BEGIN: "450"  # 7:30
  TRANSMISSION_ALT_SPEED_TIME_END: "1350"  # 22:30
  TRANSMISSION_ALT_SPEED_TIME_DAY: "127"  # all days
  TRANSMISSION_WATCH_DIR_ENABLED: "false"
  WEBPROXY_ENABLED: "false"
