apiVersion: v1
data:
  LOCAL_NETWORK: 192.168.2.0/24
  LOG_TO_STDOUT: "true"
  NORDVPN_COUNTRY: CH
  OPENVPN_OPTS: --inactive 3600 --ping 10 --ping-exit 60 --mssfix 1452
  OPENVPN_PROVIDER: NORDVPN
  PGID: "1000"
  PUID: "1000"
  TRANSMISSION_ALT_SPEED_DOWN: "5000"
  TRANSMISSION_ALT_SPEED_TIME_BEGIN: "450"
  TRANSMISSION_ALT_SPEED_TIME_DAY: "127"
  TRANSMISSION_ALT_SPEED_TIME_ENABLED: "true"
  TRANSMISSION_ALT_SPEED_TIME_END: "1350"
  TRANSMISSION_DOWNLOAD_DIR: /download/completed
  TRANSMISSION_DOWNLOAD_QUEUE_SIZE: "2"
  TRANSMISSION_INCOMPLETE_DIR: /download/incomplete
  TRANSMISSION_RATIO_LIMIT: "1"
  TRANSMISSION_RPC_HOST_WHITELIST_ENABLED: "false"
  TRANSMISSION_RPC_WHITELIST_ENABLED: "false"
  TRANSMISSION_SPEED_LIMIT_DOWN: "10000"
  TRANSMISSION_SPEED_LIMIT_DOWN_ENABLED: "true"
  TRANSMISSION_WATCH_DIR_ENABLED: "false"
  TRANSMISSION_WEB_UI: combustion
  TZ: Europe/Berlin
  WEBPROXY_ENABLED: "false"
kind: ConfigMap
metadata:
  name: transmission-config
  namespace: multimedia
