apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  annotations:
    cnpg.io/reload: "true"
  labels:
    app.kubernetes.io/name: postgres
  name: postgres-admin
spec:
  data:
    - remoteRef:
        key: GRAFANA_DB_ADMIN_PASS
      secretKey: password
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: doppler-auth-api
  target:
    name: postgres-admin
    template:
      data:
        password: '{{ .password }}'
        username: postgres
      type: kubernetes.io/basic-auth
