---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: pocket-id
spec:
  chart:
    spec:
      chart: pocket-id
      sourceRef:
        kind: HelmRepository
        name: anza-labs
        namespace: pocket-id
      version: "1.7.2"
      interval: 5m
  interval: 5m
  timeout: 20m
  install:
    timeout: 20m
    disableWait: false
    crds: CreateReplace
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    timeout: 20m
    disableWait: false
    crds: CreateReplace
  valuesFrom:
    - kind: ConfigMap
      name: values
    - kind: Secret
      name: pg-connection
      valuesKey: connectionString
      targetPath: database.connectionString
