---
- hosts: fan
  become: true
  handlers:
  - name: restart fan service
    systemd:
      name: fan.service
      state: restarted
      enabled: true
      daemon_reload: true
  tasks:
  - name: Install required packages
    package:
      name: "python3-rpi.gpio"
      state: present
  - name: Copy fan controller script and systemd service
    copy:
      src: "{{ item.src }}"
      dest: "{{ item.dst }}"
    with_items:
      - src: "fan.py"
        dst: "/usr/local/bin/fan.py"
      - src: "fan.service"
        dst: "/etc/systemd/system/fan.service"
    notify: restart fan service

