---
roles:
- name: oefenweb.locales
  version: v1.0.52
- name: hifis.unattended_upgrades
  version: v3.2.1
- name: paulfantom.system

collections:
- name: devsec.hardening
  version: 10.5.0
- name: prometheus.prometheus
  version: 0.27.6
