apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  annotations:
    cnpg.io/reload: "true"
  labels:
    app.kubernetes.io/name: postgres
  name: postgres-user
spec:
  data:
    - remoteRef:
        key: POCKET_ID_DB_PASS
      secretKey: password
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: doppler-auth-api
  target:
    name: postgres-user
    template:
      data:
        password: '{{ .password }}'
        username: pocketid
      type: kubernetes.io/basic-auth
