apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: pocket-id
resources:
  - backup.yaml
  - cluster.yaml
  - credentialsAdmin.yaml
  - credentialsBackup.yaml
  - credentialsUser.yaml
